ComputerServicesWeb/ComputerServicesWeb/Controllers/UsedMachinesController.cs
using ComputerServicesWeb.Infrastructure;
using ComputerServicesWeb.Models;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;
using PagedList;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ComputerServicesWeb.Controllers
{
    [CustomAuthFilter]
    public class UsedMachinesController : Controller
    {
        ApplicationDbContext _db = new ApplicationDbContext();

        #region Used Machines
        public ActionResult Index()
        {
            UsedMachineModels obj = new UsedMachineModels();

            obj.Types = new SelectList(_db.types.ToList(), "id", "TypeName");
            obj.ArabicTypes = new SelectList(_db.types.ToList(), "id", "ArabicTypeName");
            return View(obj);
        }
        [HttpPost]
        public ActionResult MachineInformation(FormCollection form, HttpPostedFileBase[] file)
        {

            string _path = "";
            string FileName = "";
            string combinefilenames = "";

            if (file.Length > 0)
            {
                foreach (var item in file)
                {
                    FileName = Path.GetFileNameWithoutExtension(item.FileName);
                    string Extension = Path.GetExtension(item.FileName);

                    FileName = FileName + DateTime.Now.ToString("yymmssfff") + Extension;


                    _path = Path.Combine(Server.MapPath("~/Uploads"), FileName);
                    item.SaveAs(_path);
                    if (combinefilenames == "")
                    {
                        combinefilenames += "/Uploads/" + FileName;
                    }
                    else
                    {
                        combinefilenames += "," + "/Uploads/" + FileName;
                    }

                }
            }

            var type = 0;

            if (form["ListofType"] != null)
            {
                type = Convert.ToInt32(form["ListofType"]);

            }
            else if (form["ArabicListofType"] != null)
            {
                type = Convert.ToInt32(form["ArabicListofType"]);
            }
            var obj = new UsedMachineModels
            {
                usedmachineId =form["usedmachineId"],
                Brand = form["Brand"].ToString(),
                Harddisk = form["Harddisk"].ToString(),
                PicturePath = combinefilenames,
                ModelNo = form["ModelNo"].ToString(),
                OtherInformation = form["OtherInformation"].ToString(),
                Processor = form["Processor"].ToString(),
                Ram = form["Ram"].ToString(),
                ScreenSize = form["ScreenSize"].ToString(),
                Type = type,
                ArabicBrand = form["ArabicBrand"].ToString(),
                ArabicHarddisk = form["ArabicHarddisk"].ToString(),
                ArabicModelNo = form["ArabicModelNo"].ToString(),
                ArabicOtherInformation = form["ArabicOtherInformation"].ToString(),
                ArabicProcessor = form["ArabicProcessor"].ToString(),
                ArabicRam = form["ArabicRam"].ToString(),
                ArabicScreenSize = form["ArabicScreenSize"].ToString(),
                Status = "Active"

            };

            _db.usedMachines.Add(obj);
            _db.SaveChanges();

            TempData["Message"] = "Post Posted Successfully ";

            return RedirectToAction("GetAllUsedMachines");

        }
        public ActionResult GetAllUsedMachines()
        {
            var model = _db.usedMachines.OrderByDescending(x => x.id).ToList();
            return View(model);
        }
        [HttpGet]
        public ActionResult GetAllUsedMachines(int? pageNumber)
        {
            var records = _db.usedMachines.OrderByDescending(x => x.id).ToList().ToPagedList(pageNumber ?? 1, 6);
            return View(records);
        }
        public ActionResult GetusedMachinesById(int usedMachine_ID)
        {
            var model = _db.usedMachines.Where(x => x.id == usedMachine_ID).SingleOrDefault();
            string value = string.Empty;
            value = JsonConvert.SerializeObject(model, Formatting.Indented, new JsonSerializerSettings
            {
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore
            });
            return Json(value, JsonRequestBehavior.AllowGet);
        }
        public ActionResult UpdateusedMachine(string data, HttpPostedFileBase[] file)
        {
            UsedMachineModels model = JsonConvert.DeserializeObject<UsedMachineModels>(data);
            string FileName = "";
            string _path = "";
            string combinefilenames = "";


            if (file != null)
            {

                if (file.Length > 0)
                {
                    foreach (var item in file)
                    {
                        FileName = Path.GetFileNameWithoutExtension(item.FileName);
                        string Extension = Path.GetExtension(item.FileName);

                        FileName = FileName + DateTime.Now.ToString("yymmssfff") + Extension;


                        _path = Path.Combine(Server.MapPath("~/Uploads"), FileName);
                        item.SaveAs(_path);
                        if (combinefilenames == "")
                        {
                            combinefilenames += "/Uploads/" + FileName;
                        }
                        else
                        {
                            combinefilenames += "," + "/Uploads/" + FileName;
                        }

                    }
                

                var usedmachine = _db.usedMachines.Where(x => x.id == model.id).FirstOrDefault();
                    usedmachine.PicturePath = combinefilenames;
                    usedmachine.Brand = model.Brand;
                    usedmachine.Harddisk = model.Harddisk;
                    usedmachine.Type = model.Type;
                    usedmachine.ScreenSize = model.ScreenSize;
                    usedmachine.Ram = model.Ram;
                    usedmachine.Processor = model.Processor;
                    usedmachine.OtherInformation = model.OtherInformation;
                    usedmachine.ModelNo = model.ModelNo;
                    usedmachine.ArabicBrand = model.ArabicBrand;
                    usedmachine.ArabicHarddisk = model.ArabicHarddisk;
                    usedmachine.ArabicScreenSize = model.ArabicScreenSize;
                    usedmachine.ArabicRam = model.ArabicRam;
                    usedmachine.ArabicProcessor = model.ArabicProcessor;
                    usedmachine.ArabicOtherInformation = model.ArabicOtherInformation;
                    usedmachine.ArabicModelNo = model.ArabicModelNo;
                    usedmachine.Status = model.Status;
                    usedmachine.Price = model.Price;

                    _db.Entry(usedmachine).State = System.Data.Entity.EntityState.Modified;
                    _db.SaveChanges();
                }
            }
            else
            {
                var usedmachine = _db.usedMachines.Where(x => x.id == model.id).FirstOrDefault();
                usedmachine.PicturePath = model.existingpicturepath;
                usedmachine.Brand = model.Brand;
                usedmachine.Harddisk = model.Harddisk;
                usedmachine.Type = model.Type;
                usedmachine.ScreenSize = model.ScreenSize;
                usedmachine.Ram = model.Ram;
                usedmachine.Processor = model.Processor;
                usedmachine.OtherInformation = model.OtherInformation;
                usedmachine.ModelNo = model.ModelNo;
                usedmachine.ArabicBrand = model.ArabicBrand;
                usedmachine.ArabicHarddisk = model.ArabicHarddisk;
                usedmachine.ArabicScreenSize = model.ArabicScreenSize;
                usedmachine.ArabicRam = model.ArabicRam;
                usedmachine.ArabicProcessor = model.ArabicProcessor;
                usedmachine.ArabicOtherInformation = model.ArabicOtherInformation;
                usedmachine.Status = model.Status;
                usedmachine.ArabicModelNo = model.ArabicModelNo;
                usedmachine.Price = model.Price;

                _db.Entry(usedmachine).State = System.Data.Entity.EntityState.Modified;
                _db.SaveChanges();
            }

            return Json(true, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult UsedMachineDelete(int id)
        {
            var usedMachine = _db.usedMachines.Where(x => x.id == id).FirstOrDefault();
            _db.usedMachines.Remove(usedMachine);
            _db.SaveChanges();

            return Json(true, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult AjaxMethodForDropDown(string name)
        {
            List<SelectListItem> dropdown = (from dropdowns in this._db.types.Take(20)
                                             select new SelectListItem
                                             {
                                                 Value = dropdowns.id.ToString(),
                                                 Text = dropdowns.TypeName,

                                             }).ToList();
            return Json(dropdown);
        }

        [HttpPost]
        public JsonResult AjaxMethodForArabicDropDown(string name)
        {
            List<SelectListItem> dropdown = (from dropdowns in this._db.types.Take(20)
                                             select new SelectListItem
                                             {
                                                 Value = dropdowns.id.ToString(),
                                                 Text = dropdowns.ArabicTypeName,

                                             }).ToList();
            return Json(dropdown);
        }

        #endregion

        #region Services Actions
        public ActionResult Services()

ComputerServicesWeb/ComputerServicesWeb/Views/UsedMachines/Index.cshtml
@model ComputerServicesWeb.Models.UsedMachineModels
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!--begin::Toolbar-->
<div id="kt_app_toolbar" class="app-toolbar py-3 py-lg-6">
    <!--begin::Toolbar container-->
    <div id="kt_app_toolbar_container" class="app-container container-fluid d-flex flex-stack">
        <!--begin::Page title-->
        <div class="page-title d-flex flex-column justify-content-center flex-wrap me-3">
            <!--begin::Title-->
            <h1 class="page-heading d-flex text-dark fw-bold fs-3 flex-column justify-content-center my-0">Default</h1>
            <!--end::Title-->
            <!--begin::Breadcrumb-->
            <ul class="breadcrumb breadcrumb-separatorless fw-semibold fs-7 my-0 pt-1">
                <!--begin::Item-->
                <li class="breadcrumb-item text-muted">
                    <a href="../../demo1/dist/index.html" class="text-muted text-hover-primary">Home</a>
                </li>
                <!--end::Item-->
                <!--begin::Item-->
                <li class="breadcrumb-item">
                    <span class="bullet bg-gray-400 w-5px h-2px"></span>
                </li>
                <!--end::Item-->
                <!--begin::Item-->
                <li class="breadcrumb-item text-muted">Dashboards</li>
                <!--end::Item-->
            </ul>
            <!--end::Breadcrumb-->
        </div>
        <!--end::Page title-->

    </div>
    <!--end::Toolbar container-->
</div>
<!--end::Toolbar-->
<!--begin::Content-->
<div id="kt_app_content" class="app-content flex-column-fluid">
    <!--begin::Content container-->
    <div id="kt_app_content_container" class="app-container container-fluid">
        <div>


            @using (Html.BeginForm("MachineInformation", "UsedMachines", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <div class="mb-3">
                    <label for="usedMachineId" class="form-label">Post Name:/:اسم الوظيفة</label>
                    @Html.TextBoxFor(m => m.usedmachineId,"", new { @class = "form-control", id = "usedMachineId",type="text" })
                </div>
                <div class="row fv-row">
                    <div class="col-6">
                        <label for="BrandName" class="form-label">Brand Name:</label>
                        @Html.TextBoxFor(m => m.Brand, new { @class = "form-control", id = "BrandName", required = "required" })
                    </div>
                    <div class="col-6">
                        <label for="ArabicBrandName" class="form-label"><b>:اسم العلامة التجارية</b></label>
                        @Html.TextBoxFor(m => m.ArabicBrand, new { @class = "form-control", id = "ArabicBrandName", dir = "rtl" })
                    </div>
                </div>

                <div class="mb-3">
                    <label for="SelectPicture" class="form-label">Upload Picture:/:تحميل الصورة</label>
                    @Html.TextBox("file", "", new { type = "file", @class = "form-control", id = "SelectPicture", multiple = "multiple", required = "required" })
                </div>

                <div class="row fv-row">
                    <div class="col-6">
                        <label  class="form-label">Type:</label>
                        @Html.DropDownList("ListofType", Model.Types, "Please Select Any Type", new { @class = "form-control", required = "required" })
                    </div>
                    <div class="col-6">
                        <label  class="form-label"><b>:يكتب</b></label>
                        @Html.DropDownList("ArabicListofType", Model.ArabicTypes, "الرجاء تحديد أي نوع", new { @class = "form-control", dir = "rtl" })
                    </div>
                </div>
                <div class="row fv-row">
                    <div class="col-6">
                        <label for="Ram" class="form-label">Ram:</label>
                        @Html.TextBoxFor(m => m.Ram, new { @class = "form-control", id = "Ram" })
                    </div>
                    <div class="col-6">
                        <label for="ArabicRam" class="form-label"><b>:كبش</b></label>
                        @Html.TextBoxFor(m => m.ArabicRam, new { @class = "form-control", id = "ArabicRam", dir = "rtl" })
                    </div>
                </div>
                <div class="row fv-row">
                    <div class="col-6">
                        <label for="Harddisk" class="form-label">Hard Disk:</label>
                        @Html.TextBoxFor(m => m.Harddisk, new { @class = "form-control", id = "Harddisk" })
                    </div>
                    <div class="col-6">
                        <label for="ArabicHarddisk" class="form-label"><b>:القرص الصلب</b></label>
                        @Html.TextBoxFor(m => m.ArabicHarddisk, new { @class = "form-control", id = "ArabicHarddisk", dir = "rtl" })
                    </div>
                </div>
                <div class="row fv-row">
                    <div class="col-6">
                        <label for="ScreenSize" class="form-label">Screen Size:</label>
                        @Html.TextBoxFor(m => m.ScreenSize, new { @class = "form-control", id = "ScreenSize" })
                    </div>
                    <div class="col-6">
                        <label for="ArabicScreenSize" class="form-label"><b>:حجم الشاشة</b></label>
                        @Html.TextBoxFor(m => m.ArabicScreenSize, new { @class = "form-control", id = "ArabicScreenSize", dir = "rtl" })
                    </div>
                </div>
                <div class="row fv-row">
                    <div class="col-6">
                        <label for="ModelNo" class="form-label">Model No:</label>
                        @Html.TextBoxFor(m => m.ModelNo, new { @class = "form-control", id = "ModelNo" })
                    </div>
                    <div class="col-6">
                        <label for="ArabicModelNo" class="form-label"><b>:نموذج رقم</b></label>
                        @Html.TextBoxFor(m => m.ArabicModelNo, new { @class = "form-control", id = "ArabicModelNo", dir = "rtl" })
                    </div>
                </div>
                <div class="row fv-row">
                    <div class="col-6">
                        <label for="Processor" class="form-label">Processor:</label>
                        @Html.TextBoxFor(m => m.Processor, new { @class = "form-control", id = "Processor" })
                    </div>
                    <div class="col-6">
                        <label for="ArabicProcessor" class="form-label"><b>:المعالج</b></label>
                        @Html.TextBoxFor(m => m.ArabicProcessor, new { @class = "form-control", id = "ArabicProcessor", dir = "rtl" })
                    </div>
                </div>
                <div class="row fv-row">
                    <div class="col-6">
                        <label for="OtherInfo" class="form-label">Other Information:</label>
                        @Html.TextAreaFor(m => m.OtherInformation, new { @class = "form-control", id = "OtherInfo", maxlength = "50" })
                    </div>
                    <div class="col-6">
                        <label for="ArabicOtherInformation" class="form-label"><b>:معلومات أخرى</b></label>
                        @Html.TextAreaFor(m => m.ArabicOtherInformation, new { @class = "form-control", id = "ArabicOtherInformation", maxlength = "50", dir = "rtl" })
                    </div>
                </div>
                <div class="text-center pt-15">
                    <button type="submit" class="btn btn-primary">Submit/<b>يُقدِّم</b></button>
                </div>
            }

        </div>
    </div>
    <!--end::Content container-->
</div>
<!--end::Content-->

ComputerServicesWeb/ComputerServicesWeb/Views/UsedMachines/Services.cshtml
@model ComputerServicesWeb.Models.ServicesModel

@{
    ViewBag.Title = "Services";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!--begin::Toolbar-->
<div id="kt_app_toolbar" class="app-toolbar py-3 py-lg-6">
    <!--begin::Toolbar container-->
    <div id="kt_app_toolbar_container" class="app-container container-fluid d-flex flex-stack">
        <!--begin::Page title-->
        <div class="page-title d-flex flex-column justify-content-center flex-wrap me-3">
            <!--begin::Title-->
            <h1 class="page-heading d-flex text-dark fw-bold fs-3 flex-column justify-content-center my-0">Services</h1>
            <!--end::Title-->
            <!--begin::Breadcrumb-->
            <ul class="breadcrumb breadcrumb-separatorless fw-semibold fs-7 my-0 pt-1">
                <!--begin::Item-->
                <li class="breadcrumb-item text-muted">
                    <a href="" class="text-muted text-hover-primary">Home</a>
                </li>
                <!--end::Item-->
                <!--begin::Item-->
                <li class="breadcrumb-item">
                    <span class="bullet bg-gray-400 w-5px h-2px"></span>
                </li>
                <!--end::Item-->
                <!--begin::Item-->
                <li class="breadcrumb-item text-muted">Dashboards</li>
                <!--end::Item-->
            </ul>
            <!--end::Breadcrumb-->
        </div>
        <!--end::Page title-->

    </div>
    <!--end::Toolbar container-->
</div>
<!--end::Toolbar-->
<!--begin::Content-->
<div id="kt_app_content" class="app-content flex-column-fluid">
    <!--begin::Content container-->
    <div id="kt_app_content_container" class="app-container container-fluid">
        <div>


            @using (Html.BeginForm("Services", "UsedMachines", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <div class="row fv-row">
                    <div class="col-6">
                        <label for="ServiceName" class="form-label">Service Name:</label>
                        @Html.TextBoxFor(m => m.Name, new { @class = "form-control", id = "ServiceName", required = "required" })
                    </div>
                    <div class="col-6">
                        <label for="ServiceName" class="form-label" >:اسم الخدمة</label>
                        @Html.TextBoxFor(m => m.ArabicName, new { @class = "form-control", id = "ArabicServiceName", dir = "rtl" })
                    </div>
                </div>
                <div class="mb-3">
                    <label for="SelectPicture" class="form-label">Upload Picture:</label>
                    @Html.TextBox("file", "", new { type = "file", @class = "form-control", id = "SelectPicture", required = "required" })
                </div>
                <div class="row fv-row">
                    <div class="col-6">
                        <label for="Description" class="form-label">Services Description:</label>
                        @Html.TextBoxFor(m => m.Description, new { @class = "form-control", id = "Description" })
                    </div>
                    <div class="col-6">
                        <label for="Description" class="form-label">:وصف الخدمات</label>
                        @Html.TextBoxFor(m => m.ArabicDescription, new { @class = "form-control", id = "ArabicDescription", dir = "rtl" })
                    </div>
                </div>
                <div class="text-center pt-15">
                    <button type="submit" class="btn btn-primary">Submit/يُقدِّم</button>
                </div>
            }

        </div>
    </div>
    <!--end::Content container-->
</div>
<!--end::Content-->