ComputerServicesWeb/ComputerServicesWeb/Controllers/AssignRoleController.cs
using ComputerServicesWeb.Infrastructure;
using ComputerServicesWeb.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using static ComputerServicesWeb.ApplicationSignInManager;

namespace ComputerServicesWeb.Controllers
{
    [CustomAuthFilter]
    public class AssignRoleController : Controller
    {
        // GET: AssignRole
        ApplicationDbContext _dbcontext = new ApplicationDbContext();
        //log4net.ILog errlogger = log4net.LogManager.GetLogger("ErrorLogFile");


        public ActionResult Index()
        {
            List<SelectListItem> roles=new List<SelectListItem>();
            List<SelectListItem> users=new List<SelectListItem>();

            using (var context = new ApplicationDbContext())
            {
                var Roles = context.Roles;
                var Users = context.Users;

                foreach(var role in Roles)
                {
                    //var name = role.Name;
                    roles.Add(new SelectListItem { Text = role.Name, Value = role.Id });
                }

                foreach(var user in Users)
                {
                    users.Add(new SelectListItem { Text = user.UserName, Value = user.Id });
                }
            }
            ViewBag.RolesList = roles;
            ViewBag.UsersList = users;
            return View();
        }
        
        [HttpPost]
        public ActionResult Assign(FormCollection form)
        {
            try
            {
                if (form.Count > 0)
                {
                    var role_id = form["RolesList"].ToString();
                    var User_id = form["UsersList"].ToString();

                    //check if user exist
                    int count = _dbcontext.UserRoles.Where(x => x.UserId == User_id).Count();

                    //if user not exist add user to database with current role.Else delete user with old role and then add user with new role.
                    if (count == 0)
                    {
                        _dbcontext.UserRoles.Add(new IdentityUserRole { RoleId = role_id, UserId = User_id });
                        _dbcontext.SaveChanges();
                    }
                    else
                    {
                        var user = _dbcontext.UserRoles.Where(x => x.UserId == User_id).FirstOrDefault();
                        _dbcontext.UserRoles.Remove(user);
                        _dbcontext.SaveChanges();

                        _dbcontext.UserRoles.Add(new IdentityUserRole { RoleId = role_id, UserId = User_id });
                        _dbcontext.SaveChanges();
                    }

                    DisplayUserInfo.role = _dbcontext.Roles.Where(x => x.Id == role_id).Select(x=>x.Name).Single();
                }
            }
            catch (Exception ex)
            {
                //errlogger.Error(ex.Message);
            }
            return RedirectToAction("Index");
        }
    }
}

ComputerServicesWeb/ComputerServicesWeb/Views/AssignRole/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!--begin::Toolbar-->
<div id="kt_app_toolbar" class="app-toolbar py-3 py-lg-6">
    <!--begin::Toolbar container-->
    <div id="kt_app_toolbar_container" class="app-container container-fluid d-flex flex-stack">
        <!--begin::Page title-->
        <div class="page-title d-flex flex-column justify-content-center flex-wrap me-3">
            <!--begin::Title-->
            <h1 class="page-heading d-flex text-dark fw-bold fs-3 flex-column justify-content-center my-0">Default</h1>
            <!--end::Title-->
            <!--begin::Breadcrumb-->
            <ul class="breadcrumb breadcrumb-separatorless fw-semibold fs-7 my-0 pt-1">
                <!--begin::Item-->
                <li class="breadcrumb-item text-muted">
                    <a href="../../demo1/dist/index.html" class="text-muted text-hover-primary">Home</a>
                </li>
                <!--end::Item-->
                <!--begin::Item-->
                <li class="breadcrumb-item">
                    <span class="bullet bg-gray-400 w-5px h-2px"></span>
                </li>
                <!--end::Item-->
                <!--begin::Item-->
                <li class="breadcrumb-item text-muted">Dashboards</li>
                <!--end::Item-->
            </ul>
            <!--end::Breadcrumb-->
        </div>
        <!--end::Page title-->

    </div>
    <!--end::Toolbar container-->
</div>
<!--end::Toolbar-->
<!--begin::Content-->
<div id="kt_app_content" class="app-content flex-column-fluid">
    <!--begin::Content container-->
    <div id="kt_app_content_container" class="app-container container-fluid">
        <div>

            @using (Html.BeginForm("Assign", "AssignRole", FormMethod.Post))
            {
                <div class="form-group">
                    <label for="RolesList">Role</label>
                    @Html.DropDownList("RolesList", (IEnumerable<SelectListItem>)ViewBag.RolesList, new { @class = "form-control" })
                </div>

                <div class="form-group">
                    <label for="UsersList">User</label>
                    @Html.DropDownList("UsersList", (IEnumerable<SelectListItem>)ViewBag.UsersList, new { @class = "form-control" })
                </div>

                <br />

                <button type="submit" class="btn btn-primary">Assign</button>

            }
        </div>
    </div>
    <!--end::Content container-->
</div>
<!--end::Content-->